#!/bin/bash

UPDATE_FILE=/var/lib/update-notifier/updates-available

if grep -i "security updates" "${UPDATE_FILE}"
then
	exit 1
fi

if grep -i "can be updated" "${UPDATE_FILE}"
then
	exit 1
fi

if grep -i "restart required" "${UPDATE_FILE}"
then
	exit 1
fi

echo "OK: packages up-to-date"
exit 0

