#!/bin/bash

UPDATE_FILE=/var/lib/update-notifier/updates-available
SUMMARY=`cat ${UPDATE_FILE}`
SUMMARY=`echo ${SUMMARY}`
OUTPUT="OK: Packages up-to-date"

if [[ $SUMMARY =~ "^([0-9]+) packages can be updated\. ([0-9]+) updates are security updates." ]]
then

  if [ "${BASH_REMATCH[1]}" != "0" ]
  then
    OUTPUT="${BASH_REMATCH[1]} Updates. ${BASH_REMATCH[2]} Security."
    RETCODE=1
  fi

fi

if [ -f /var/run/reboot-required ]
then
  OUTPUT="Reboot required. ${OUTPUT}"
  RETCODE=2
fi

echo "$OUTPUT"
exit $RETCODE

